use `bumblebee`;
DELETE from user;
INSERT INTO `user` (id,name,email,password,status) VALUES (0,'admin','admin@localhost','admin',1),
                                                       (1,'user','user@localhost','user',1),
                                                       (2,'guest','guest@localhost','guest',1),
                                                       (3,'test','test@localhost','test',1);
DELETE from `flower`;
INSERT INTO `flower` (id,name,description, code, image_path, pollen, nectar, x, y)
VALUES (0,'érable champêtre','Acer campestris','ABCD','acer_campestre.jpg',3,2,0,0),
    (1,'érable sycomore','Acer pseudoplatanus','ABCD','acer_pseudoplatanus.jpg',2,2,0,0),
(2,'aulne glutineux','Alnus glutinosa','ABCD','alnus_glutinosa.jpg',1,2,0,0),
(3,'ancolie','Aquilegia vulgaris','ABCD','aquilegia_vulgaris.jpg',2,3,0,0),
(4,'herbe à la ouate','Asclépias syriaca ','ABCD','photo',3,1,0,0),
(5,'épine vinette','Berberis vulgaris','ABCD','photo',2,1,0,0),
(6,'bourrache officinalis ','Borago officinalis','ABCD','photo',3,2,0,0),
(7,'moutarde des champs','brassica arvensis ','ABCD','photo',3,1,0,0),
(8,'bruyère commune callune','Calluna vulgaris','ABCD','calluna_vulgaris.jpg',2,1,0,0),
(9,'noisetier de Bysance','Corylus colurna','ABCD','corylus_colurna.jpg',0,1,0,0),
(10,'cotoneaster ','Cotoneaster horizontalis','ABCD','cotoneaster_horizon_talis.jpg',3,2,0,0),
(11,'crocus de printemps','Crocus vernus ','ABCD','crocus_vernus.jpg',1,2,0,0),
(12,'dalhia CV','Dalhia variabilis','ABCD','dalhia_variabilis.jpg',0,2,0,0),
(13,'epilobe en épis','Epilobium angustifolium','ABCD','epilobium_angustifolium.jpg',3,2,0,0),
(14,'sarrasin ou blé noir','Fagopyrum esculentum','ABCD','fagopryrum_esculentum.jpeg',2,1,0,0),
(15,'frêne à fleurs','Fraxinus ornus','ABCD','fraxinus_ornus.jpg',1,2,0,0),
(16,'févier','Gleditsia triacanthos','ABCD','gleditsia_triacanthos.jpg',2,0,0,0),
(17,'lierre','Hedera helix','ABCD','dedera_helix.jpg',3,3,0,0),
(18,'Lavandula officinale','Lavandula officinale','ABCD','lavande_officinale.jpg',3,1,0,0),
(19,'chèvrefeuille','Lonicera tartarica','ABCD','lonicera_tartanrica.jpg',2,2,0,0),
(20,'luzerne cultivée','Médicago sativa','ABCD','medicago_sativa.jpg',3,1,0,0),
(21,'phacelie à feuilles de tanaisie','Phacelia tanacetifolia ','ABCD','phacelia_tanacetifolia.jpg',3,2,0,0),
(22,'merisier','Prunus avium','ABCD','prunus_avium.jpeg',2,3,0,0),
(23,'prunellier','Prunus spinosa','ABCD','prunus_spinosa.jpg',2,2,0,0),
(24,'buisson ardent','Pyracantha coccinéa','ABCD','pyracantha_coccinea.jpg',2,3,0,0),
(25,'robinier faux acacia ','Robinia pseudoacacia','ABCD','robinia_pseudoacacia.jpg',3,2,0,0),
(26,'rudbeckia lacinié','Rudbeckia laciniata  ','ABCD','rudbeckia_laciniata.jpg',0,3,0,0),
(27,'saule marsault','Salix capréa','ABCD','salix_caprea.jpg',2,3,0,0),
(28,"verge d'or",'Solidago virgaurea','ABCD','solidago_virgaurea.jpg',2,2,0,0),
(29,'sophora du japon','Sophora japonica','ABCD','sophera_japonica.jpg',3,1,0,0),
(30,'pissenlit','Taraxacum officinalis','ABCD','taraxacum_officinale.jpg',3,3,0,0),
(31,'thym','Thymus vulgaris','ABCD','thymus_vulgaris',3,0,0,0),
(32,'tilleul de Henry','Tilia henryana','ABCD','tilia_henryana.jpg',3,2,0,0),
(33,'tilleul à larges feuilles','Tilia platyphillos','ABCD','tilia_platyphyllos',3,2,0,0),
(34,' trèfle blanc','Trifolium repens','ABCD','trifolium_repens.jpg',3,2,0,0),
(35,'petite pervenche','Vinca minor','ABCD','vinca_minor.jpg',2,0,0,0);


